### PR TITLE
fixes for OF09 and x64 binary

### PR DESCRIPTION
**Pull request by memoakten**
Two fixes in one (both are needed for OF09 with x64 in xcode).
I have them in separate branches as well if you want.
https://github.com/memo/ofxLibdc/tree/fix-x64
https://github.com/memo/ofxLibdc/tree/fix-of09

let me know when you merge, I'll delete all of these branches.

ta

### CODE REVIEW

**Comment by kylemcdonald** [comment]
thanks! i will merge when the final 0.9.0 release happens.

**Comment by memo** [comment]
ok makes sense. Maybe worthwhile having branches? i.e. a branch for current OF latest release, and a branch for current OF head. So those working with OF head can use the addon as well as those working with packaged download. Also when OF0.9.0 is released, probably best to have a branch 
(or maybe using tags instead of branch). 
In fact I'm trying to figure out a system like this for my own addons, but haven't figured out a good convention yet. In fact, now that I think about it, maybe tags are the best way forward: addon master is always latest, and matches OF master head. And then use tags to mark older OF releases. Though I'm not sure how that will handle cases where a new fix to the addon could work on older versions too. complex.

**Comment by gonzzza007** [comment]
Don't forget to merge this pull request :)

**Comment by kylemcdonald** [comment]
thanks @memo and @gonzzza007 !

**Pull request merged**
